arch = [
  "accountsservice",
  "alacritty",
  "alsa-firmware",
  "alsa-plugins",
  "alsa-utils",
  "amd-ucode",
  "ark",
  "awesome-terminal-fonts",
  "base",
  "base-devel",
  "bash-completion",
  "bind",
  "bluedevil",
  "bluez",
  "bluez-hid2hci",
  "bluez-libs",
  "bluez-utils",
  "breeze-gtk",
  "btrfs-assistant",
  "btrfs-progs",
  "cachyos-emerald-kde-theme-git",
  "cachyos-fish-config",
  "cachyos-gaming-applications",
  "cachyos-gaming-meta",
  "cachyos-hello",
  "cachyos-hooks",
  "cachyos-iridescent-kde",
  "cachyos-kde-settings",
  "cachyos-kernel-manager",
  "cachyos-keyring",
  "cachyos-micro-settings",
  "cachyos-mirrorlist",
  "cachyos-nord-kde-theme-git",
  "cachyos-packageinstaller",
  "cachyos-plymouth-bootanimation",
  "cachyos-rate-mirrors",
  "cachyos-settings",
  "cachyos-snapper-support",
  "cachyos-themes-sddm",
  "cachyos-v3-mirrorlist",
  "cachyos-v4-mirrorlist",
  "cachyos-wallpapers",
  "cantarell-fonts",
  "cgal",
  "char-white",
  "chwd",
  "cryptsetup",
  "debuginfod",
  "device-mapper",
  "dhclient",
  "dmidecode",
  "dmraid",
  "dnsmasq",
  "dosfstools",
  "duf",
  "e2fsprogs",
  "efibootmgr",
  "efitools",
  "egl-wayland",
  "entr",
  "ethtool",
  "exfatprogs",
  "f2fs-tools",
  "f3d",
  "fastfetch",
  "ffmpegthumbnailer",
  "ffmpegthumbs",
  "filelight",
  "foomatic-db",
  "foomatic-db-engine",
  "foomatic-db-gutenprint-ppds",
  "foomatic-db-nonfree",
  "foomatic-db-nonfree-ppds",
  "foomatic-db-ppds",
  "foot",
  "fsarchiver",
  "fwupd",
  "ghostscript",
  "glances",
  "gsfonts",
  "gst-libav",
  "gst-plugin-pipewire",
  "gst-plugin-va",
  "gst-plugins-bad",
  "gst-plugins-ugly",
  "gutenprint",
  "gwenview",
  "haruna",
  "haveged",
  "hdparm",
  "inetutils",
  "iptables-nft",
  "itstool",
  "iwd",
  "jfsutils",
  "kate",
  "kcalc",
  "kde-gtk-config",
  "kdeconnect",
  "kdegraphics-thumbnailers",
  "kdenlive",
  "kdeplasma-addons",
  "kdialog",
  "kinfocenter",
  "kio-admin",
  "kscreen",
  "kwallet-pam",
  "kwalletmanager",
  "less",
  "lib32-mesa",
  "lib32-opencl-mesa",
  "lib32-openssl-1.0",
  "lib32-openssl-1.1",
  "lib32-vulkan-radeon",
  "libdvdcss",
  "libgsf",
  "libopenraw",
  "libplasma",
  "libwnck3",
  "limine",
  "limine-mkinitcpio-hook",
  "limine-snapper-sync",
  "linux-cachyos",
  "linux-cachyos-headers",
  "linux-cachyos-lts",
  "linux-cachyos-lts-headers",
  "linux-firmware",
  "linux-tools-meta",
  "logrotate",
  "lsb-release",
  "lsscsi",
  "lvm2",
  "ly",
  "man-db",
  "man-pages",
  "mdadm",
  "micro",
  "mkinitcpio",
  "modemmanager",
  "mtools",
  "nano-syntax-highlighting",
  "netctl",
  "networkmanager",
  "networkmanager-openvpn",
  "nfs-utils",
  "nilfs-utils",
  "noto-color-emoji-fontconfig",
  "noto-fonts",
  "noto-fonts-cjk",
  "noto-fonts-emoji",
  "nss-mdns",
  "ntp",
  "octopi",
  "opencl-mesa",
  "openssh",
  "openssl-1.0",
  "openssl-1.1",
  "os-prober",
  "pacman-contrib",
  "paru",
  "phonon-qt6-vlc",
  "pipewire-alsa",
  "pipewire-pulse",
  "pkgfile",
  "plasma-browser-integration",
  "plasma-desktop",
  "plasma-firewall",
  "plasma-integration",
  "plasma-nm",
  "plasma-pa",
  "plasma-systemmonitor",
  "plasma-thunderbolt",
  "plasma-workspace",
  "plocate",
  "plymouth",
  "plymouth-kcm",
  "poppler-glib",
  "power-profiles-daemon",
  "powerdevil",
  "pv",
  "python-defusedxml",
  "python-packaging",
  "qt5-feedback",
  "qt5-graphicaleffects",
  "qt5-imageformats",
  "qt5-location",
  "qt5-networkauth",
  "qt5-quickcontrols",
  "qt5-quickcontrols-nemo",
  "qt5-script",
  "qt5-sensors",
  "qt5-serialport",
  "qt5-speech",
  "qt5-svg",
  "qt5-systems",
  "qt5-tools",
  "qt5-virtualkeyboard",
  "qt5-webchannel",
  "qt5-xcb-private-headers",
  "qt5-xmlpatterns",
  "qt5ct",
  "qt5pas",
  "qt6-wayland",
  "rebuild-detector",
  "reflector",
  "rtkit",
  "s-nail",
  "sddm",
  "sddm-kcm",
  "sg3_utils",
  "smartmontools",
  "snapper",
  "sof-firmware",
  "spectacle",
  "splix",
  "sysfsutils",
  "system-config-printer",
  "texinfo",
  "ttf-bitstream-vera",
  "ttf-dejavu",
  "ttf-liberation",
  "ttf-meslo-nerd",
  "ttf-opensans",
  "ufw",
  "upower",
  "usb_modeswitch",
  "vlc-plugins-all",
  "vulkan-radeon",
  "waybar",
  "wayland-protocols",
  "wireless-regdb",
  "wireplumber",
  "wl-clipboard",
  "wpa_supplicant",
  "xdg-desktop-portal",
  "xdg-desktop-portal-kde",
  "xdg-desktop-portal-wlr",
  "xdg-user-dirs",
  "xf86-input-libinput",
  "xf86-video-amdgpu",
  "xfsprogs",
  "xl2tpd",
  "xorg-server",
  "xorg-server-xvfb",
  "xorg-xdpyinfo",
  "xorg-xinit",
  "xorg-xinput",
  "xorg-xkill",
  "xorg-xrandr",
  "xorg-xwayland",
  "xsettingsd",
]
