arch = [
  # Core tools
  "diffutils",
  "less",
  "rsync",
  "sudo",
  "wget",
  "which",
  # HW related tools
  "cpupower",
  "hwdetect",
  "hwinfo",
  "usbutils",
  # Archives
  "unrar",
  "unzip",
  "zip",

  # Configuration
  "chezmoi",
  # Generic CLI tools
  "btop",
  "ripgrep",
  # Programming languages
  "perl",
  "python",
  "rustup",
  "uv",
  # Editors
  "helix",
  "nano",
  "vim",

]
